setTimeout(()=>{
    console.log('Request-1');
},1000)
setTimeout(()=>{
    console.log('Request-2');
},3000)
setTimeout(()=>{
    console.log('Request-3');
},6000)
setTimeout(()=>{
    console.log('Request-4');
},2000)
setTimeout(()=>{
    console.log('Request-5');
},4000)